Basic Array Creation


In [ ]:
import numpy as np

myForthArray = np.arange(5, 101, 10, np.int32)
print(myForthArray)


[ 5 15 25 35 45 55 65 75 85 95]


In [ ]:
#create an array with 10 Equally spaced number between 0 to 1
import numpy as np

arr = np.linspace(0, 1,num=10)
print(arr)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#create a 20 random integer between 1 to 100
import numpy as np
arr=np.random.randint(1,100,size=20)
print(arr)

[48  7  9 62 49 59 33 52  6 99 72 80  5 50 78 38 27 99 32 90]


In [ ]:
#create  a 2D array with the shape(4,4)filled with the value 7
import numpy as np
arr=np.full((4,4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
#create a 1D array of 10 element with the same value 3.14
arr=np.full(10,3.14)
arr=np.arange(1000)
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [ ]:
#create a 2D array with the shape(3,3)with values ranging from 1 to 9.
arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array operations

In [ ]:
#create two arrays perform element-wise subtraction
a=np.array([1,3,5,7,9])
b=np.array([2,4,6,8,10])
print(a-b)

[-1 -1 -1 -1 -1]


In [ ]:
#multiply array b by 3
a=np.array([2,4,6,8])
array=np.multiply(a,3)
print(array)

[ 6 12 18 24]


In [ ]:
#Divide array a by 2
a=np.array([10,20,30,40])
array=np.divide(a,2)
print(array)

[ 5. 10. 15. 20.]


In [ ]:
#create two arrays perform element-wise modulus
a=np.array([5,10,15])
b=np.array([2,3,4])
print(a%b)


[1 1 3]


In [ ]:
#create two array dot product
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.dot(a,b))

32


Matrix Multiplicaztion

In [ ]:
#create two array matrix multiplication
a=[[2,3],[4,5]]
b=[[1,0],[0,1]]
print("Matrix Multip")
print(np.dot(a,b))


[[2 3]
 [4 5]]


In [ ]:
#Multiply a 3x3 matrix with a 3x1 vector
import numpy as np

# Define your 3x3 matrix A
A = np.array([[1, 1, 1],
              [2, 1, 0],
              [1, 0, 1]])

# Define your 3x1 vector v
v = np.array([[1, 5, 9]]).T  # Transpose to make it a column vector

# Perform matrix multiplication
result = np.dot(A, v)

print("Result:")
print(result)
# Define your 3x1 vector v
v1 = np.array([10, 11, 12])

# Perform matrix-vector multiplication
result1 = np.dot(A, v1)
print("Result1:")
print(result1)


Result:
[[15]
 [ 7]
 [10]]
Result1:
[33 31 22]


In [ ]:
#Create a 4x4 identity matrix and multiply it by a 4x4 matrix filled with random integer.
import numpy as np
#create 4x4 identity matrix
identity_matrix = np.identity(4)
print("Identity Matrix:")
print(identity_matrix)
#create 4x4 matrix filled with random integer
random_matrix = np.random.randint(0, 10, size=(4, 4))
print("\nRandom Integer Matrix:")
print(random_matrix)
#multiply
result_matrix = np.dot(identity_matrix, random_matrix)
print("\nResult Matrix:")
print(result_matrix)


Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random Integer Matrix:
[[6 1 0 0]
 [7 0 6 1]
 [9 7 3 9]
 [8 7 3 8]]

Result Matrix:
[[6. 1. 0. 0.]
 [7. 0. 6. 1.]
 [9. 7. 3. 9.]
 [8. 7. 3. 8.]]


In [ ]:
#perform matrix multiplication on two 3x3 matrix
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[9,8,7],[6,5,4],[3,2,1]]
print("Matrix Multiplication")
print(np.dot(a,b))

Matrix Multiplication
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
#Create a 2x3 matrix and a 3x2 matrix.perform matrix multiplication.
import numpy as np

# create matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

# Calculate the dot product (matrix multiplication)
result = np.dot(A, B)

print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[ 58  64]
 [139 154]]


Broadcasting

In [ ]:
#create 1D array subtract a scalar value ,5, using broadcasting. python program
import numpy as np

# Create a 1D array
array = np.array([10, 20, 30])
scalar_value=5

# Subtract the scalar value 5 from each element in the array using broadcasting
result = array - scalar_value

print("Original array:", array)
print("Resulting array after subtracting 5:", result)


Original array: [10 20 30]
Resulting array after subtracting 5: [ 5 15 25]


In [ ]:
#Create a 3x3 array and a 3x1. Add them using broadcasting
import numpy as np
# Create a 3x3 array
array_3x3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
# Create a 3x1 array
array_3x1 = np.array([[1],[2],[3]])
# Add the arrays using broadcasting
result = array_3x3 + array_3x1
print("\nResult of Broadcasting Addition:")
print(result)



Result of Broadcasting Addition:
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [ ]:
#Divide a 4x4 array by a scalar value ,2, using broadcasting
#Create 4x4 array
array_3x3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[1, 4, 7]])
Scalar_value=2
#Divide the array by the scalar value
result=array_3x3/Scalar_value
print("\nResult of Broadcalting Dividing")
print(result)


Result of Broadcalting Dividing
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]
 [0.5 2.  3.5]]


In [ ]:
#Create a 3x3 array and add 3 to each element using broadcasting
import numpy as np
# Create a 3x3 array
array_3x3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
#add 3 value
result=array_3x3+3
print("\nResult of Broadcasting addition")
print(result)


Result of Broadcasting addition
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Multiply a 1D array of shape(5),by a 2D array of shape(5,5) using broadcasting.
import numpy as np

# create the 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Define the 2D array
array_2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

# Multiply using broadcasting
result = array_2d * array_1d[:, np.newaxis]

print("Result of multiplication:")
print(result)

Result of multiplication:
[[  1   2   3   4   5]
 [ 12  14  16  18  20]
 [ 33  36  39  42  45]
 [ 64  68  72  76  80]
 [105 110 115 120 125]]


Statistical Operations

In [ ]:
#Calculate the median of the array:data
import numpy as np
data=[1,2,3,4,5,6,7,8,9,10]
median=np.median(data)
print(median)


5.5


In [ ]:
#Calculate the mode of the array:data
import numpy as np
from scipy import stats
# Sample data array
data = np.array([1, 2, 2, 3, 4, 4, 4, 5, 6])

# Calculate the mode
mode_result = stats.mode(data)

# Print the mode
print( mode_result)


ModeResult(mode=4, count=3)


In [ ]:
#Calculate the range of the array:data
import numpy as np
data = np.array([10, 20,30,40,50])
range_of_data = np.ptp(data)
print("The range of the array is:", range_of_data)


The range of the array is: 40


In [ ]:
#Calculate the 25th percentile of the array:data*
import numpy as np

# Sample data array
data = np.array([1, 3, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate the 25th percentile
percentile_25 = np.percentile(data, 25)

print(percentile_25)


3.25


In [ ]:
#Calculate the correlation coefficient between two arrays: a = [1, 2, 3, 4, 5] and b = [2,
#4, 6, 8, 10].
import numpy as np

# Define the arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4, 6, 8, 10])

# Calculate the correlation coefficient
correlation_matrix = np.corrcoef(a, b)
correlation_coefficient = correlation_matrix[0, 1]

print("Correlation Coefficient:", correlation_coefficient)


Correlation Coefficient: 0.9999999999999999


Reshaping Arrays

In [ ]:
#Reshape a 1D array of 12 elements to a 3x4 array.
import numpy as np

# Create a 1D array with 12 elements
array_1d = np.arange(12)

# Reshape the array to 3x4
array_2d = array_1d.reshape(3, 4)

print(array_2d)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#Reshape a 2D array of shape (6, 2) to (3, 4).
import numpy as np

# Original array of shape (6, 2)
original_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

# Reshape to (3, 4)
reshaped_array = original_array.reshape(3, 4)

print("Original array:")
print(original_array)
print("\nReshaped array:")
print(reshaped_array)


Original array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Reshaped array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#Create a 4x4 array and flatten it.
import numpy as np

# Create a 4x4 array
array_4x4 = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

# Flatten the array
flattened_array = array_4x4.flatten()

print("Original 4x4 array:")
print(array_4x4)
print("\nFlattened array:")
print(flattened_array)


Original 4x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Flattened array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
#Reshape a 3D array of shape (2, 3, 4) to (4, 3, 2).
import numpy as np

# Create an array of shape (2, 3, 4)
array = np.arange(24).reshape(2, 3, 4)

# Reshape the array to shape (4, 3, 2)
reshaped_array = array.reshape(4, 3, 2)

print("Original array shape:", array.shape)
print("Reshaped array shape:", reshaped_array.shape)
print("Reshaped array:\n", reshaped_array)


Original array shape: (2, 3, 4)
Reshaped array shape: (4, 3, 2)
Reshaped array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [ ]:
#Reshape a 1D array to a 2D array with 1 row and many columns.
import numpy as np
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array to a 2D array with 1 row and many columns
array_2d = array_1d.reshape(1, -1)

print(array_2d)

[[1 2 3 4 5 6]]


Element-wise Operations

In [ ]:
#Create two arrays: a = [1, 3, 5] and b = [2, 4, 6]. Perform element-wise division.
import numpy as np
a = [1, 3, 5]
b = [2, 4, 6]
Division=np.divide(a,b)
print(Division)

[0.5        0.75       0.83333333]


In [ ]:
#Create two arrays: a = [2, 4, 6] and b = [1, 3, 5]. Perform element-wise modulus.
import numpy as np
a = [2, 4, 6]
b = [1, 3, 5]
Modulus=np.mod(a,b)
print(Modulus)

[0 1 1]


In [ ]:
#Add 10 to each element in the array: a = [1, 2, 3, 4, 5].
import numpy as np
a = [1, 2, 3, 4, 5]
add=np.add(a,10)
print(add)

[11 12 13 14 15]


In [ ]:
#Subtract 5 from each element in the array: b = [10, 20, 30, 40, 50].
import numpy as np
b = [10, 20, 30, 40, 50]
subtract=np.subtract(b,5)
print(subtract)


[ 5 15 25 35 45]


In [ ]:
#Square each element in the array: c = [1, 2, 3, 4, 5].
import numpy as np
c = np.array([1, 2, 3, 4, 5])
squared_c = np.square(c)
#squared_c=np.power(c,2)
print(squared_c)

[ 1  4  9 16 25]


Slicing and Indexing

In [307]:
#Create a 3D array: array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]. Access the element at [1, 1, 1].*****
import numpy as np
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
element_at_1=array_3d[1, 1, 1]
print(element_at_1)


11


In [308]:
#Slice the first layer of a 3D array: array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11,12]]].
import numpy as np
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
first_layer_slice = array_3d[0]
print(first_layer_slice)


[[1 2 3]
 [4 5 6]]


In [309]:
#Access all elements in the last row of the array: array_2d = [[10, 20, 30], [40, 50, 60],[70, 80, 90]].
array_2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
last_row = array_2d[-1]  # Get the last row
print(last_row)  # Output: [70, 80, 90]


[70, 80, 90]


In [310]:
#Access all elements in the first column of the array: array_2d = [[10, 20, 30], [40, 50,60], [70, 80, 90]].
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
last_row = array_2d[:,0]  #
print(last_row)  # Output: [70, 80, 90]


[10 40 70]


In [311]:
#Slice the last two rows and columns of the array: array_2d = [[10, 20, 30], [40, 50,60], [70, 80, 90]].
array_2d = np.array([[10, 20, 30], [40, 50,60], [70, 80, 90]])
Last_two_rows=array_2d[-2:,-2:]
print(Last_two_rows)
#Last_two_coloumns=array_2d[:,-2:]
#print(Last_two_coloumns)

[[50 60]
 [80 90]]


Creating Random Arrays

In [312]:
#Generate a random array of 20 elements with values between 0 and 1.
import numpy as np
random_array=np.random.randint(0,1,size=20)
print(random_array)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [313]:
#Create a 4x4 array with random integers between 10 and 20.
import numpy as np
random_array=np.random.randint(10,20,size=(4,4))
print(random_array)


[[11 11 14 13]
 [16 16 15 11]
 [11 14 15 15]
 [11 19 16 10]]


In [314]:
#Create a 3x3 array with random floats between -1 and 1.
import numpy as np
random_array=np.random.uniform(-1,1,size=(3,3))
print(random_array)

[[-0.84065213 -0.27496679 -0.01834572]
 [-0.26453934  0.43553604 -0.41390284]
 [-0.80742194  0.47100618  0.56388689]]


In [315]:
#Generate an array of 15 random integers between 100 and 200.
import numpy as np
random_array=np.random.randint(100,200,size=15)
print(random_array)

[135 121 162 174 189 133 134 102 150 117 109 123 158 185 196]


In [316]:
#Create a 5x5 array with random floats between 0 and 10.
import numpy as np
random_array=np.random.uniform(0,10,size=(5,5))
print(random_array)


[[0.39976932 2.85731735 5.55788769 4.2084747  4.51011603]
 [0.15929353 7.78987    1.94216578 4.69775769 1.62888897]
 [4.38486871 6.56087638 6.0857615  0.21009259 4.55009995]
 [5.5044334  3.13500836 8.75535349 6.07179194 7.40331975]
 [3.56399124 9.57762097 6.84605411 5.77193569 9.52111341]]


Stacking and Concatenating Arrays

In [317]:
#Vertically stack two arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].
import numpy as np
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]
stacked_array=np.vstack((a,b))
print(stacked_array)



[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [318]:
#Horizontally stack two arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].
import numpy as np
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]
stacked_array=np.hstack((a,b))
print(stacked_array)



[[1 2 5 6]
 [3 4 7 8]]


In [319]:
#Concatenate two 1D arrays: a = [1, 2, 3] and b = [4, 5, 6].
import numpy as np
a = [1, 2, 3]
b = [4, 5, 6]
Concatenated_array=np.concatenate((a,b))
print(Concatenated_array)




[1 2 3 4 5 6]


In [320]:
#Concatenate two 3x3 arrays along rows: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b = [[10,11, 12], [13, 14, 15], [16, 17, 18]].
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = [[10,11, 12], [13, 14, 15], [16, 17, 18]]
Concatenated_array=np.concatenate((a,b),axis=0)
print(Concatenated_array)




[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [321]:
#Concatenate two 3x3 arrays along columns: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b =[[10, 11, 12], [13, 14, 15], [16, 17, 18]].
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b =[[10, 11, 12], [13, 14, 15], [16, 17, 18]]
Concatenated_array=np.concatenate((a,b),axis=1)
print(Concatenated_array)


[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
